FROM ubuntu:latest
MAINTAINER Daniel J. Klein dklein@idmod.org
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        build-essential \
        apt-utils \
        gcc \
        git \
        curl \
        make \
        python3 \
        python3-pip \
        software-properties-common \
        vim \
        nvidia-cuda-toolkit \
        nvidia-cuda-dev \
        ubuntu-drivers-common \
        python3-dev \
        python3-pycuda \
        python3-setuptools \
        libmagickwand-dev \
        openssh-client \
    && pip3 install --upgrade pip \
    && apt-add-repository ppa:graphics-drivers/ppa \
    && apt-get update -y \
    && DEBIAN_FRONTEND=noninteractive ubuntu-drivers autoinstall \
    && apt-get clean
ADD requirements.txt /
RUN pip3 install -r requirements.txt

# Copy SSH key for git private repos
RUN mkdir -p /root/.ssh
ADD keys/id_rsa /root/.ssh/id_rsa
RUN chmod 600 /root/.ssh/id_rsa

# Skip Host verification for git
RUN echo "StrictHostKeyChecking no " > /root/.ssh/config

WORKDIR /root
RUN git clone git@github.com:InstituteforDiseaseModeling/history_matching.git \
    && cd history_matching \
    && python3 setup.py develop
