def populate_sample(subparsers, function):
    parser = subparsers.add_parser('sample', description='Generate parameter space samples for use in the specified'
                                                         'iteration. If this is the first iteration (0), samples'
                                                         'will be generated by LHS (use -n). Otherwise, samples will be'
                                                         'the candidate points generated at the end of the prior'
                                                         'iteration.')
    parser.add_argument('-c', '--case', dest='case_directory', type=str, required=True,
                        help='BHM case directory. Required.')
    parser.add_argument('-i', '--iteration', dest='iteration_number', type=int, required=True,
                        help='Current iteration number. Required.')
    parser.add_argument('-s', '--sample-file', dest='sample_file', type=str, default=None,
                        help='A file containing alternate samples to use (instead of LHS/prior candidates).')
    parser.add_argument('-n', '--number', dest='n_samples', type=int, required=True,
                        help='Number of parameter space points to sample in this iteration. Required.')
    parser.add_argument('-d', '--data-source', dest='data_source', type=str, required=True,
                        help='The name of the data source directory to initialize. Required.')
    parser.add_argument('-C', '--constraint-file', dest='constraint_filename', type=str,
                        help='Python file containing the top-level method \'constrain\' to be used for constraining'
                             'sample space candidates.')
    parser.set_defaults(func=function)

def populate_fit(subparsers, function):
    parser = subparsers.add_parser('fit', help='')
    parser.add_argument('-c', '--case', dest='case_directory', type=str, required=True,
                        help='BHM case directory. Required.')
    parser.add_argument('-i', '--iteration', dest='iteration_number', type=int, required=True,
                        help='Current iteration number. Required.')
    parser.add_argument('-C', '--cut-name', dest='cut_name', type=str, required=True,
                        help='Name of cut to use. Required.')
    parser.add_argument('--no-optimize-glm', dest='optimize_glm', action='store_false', default=True,
                        help='Do not force optimization of the GLM (Default: force).')
    parser.add_argument('--no-optimize-gpr', dest='optimize_gpr', action='store_false', default=True,
                        help='Do not force optimization of the GPR (Default: force).')
    parser.add_argument('--data-sources', dest='data_sources', type=str, required=True,
                        help='A CSV file detailing which directories and their configurations to use in training and'
                             'testing GLM and GPR. Required.')

    # ck4,  move this into Case object data?
    parser.add_argument('--implausibility_threshold', dest='implausibility_threshold', type=float, default=3,
                        help='The minimum sigma difference between data and fitted value to determine implausibility'
                             '(Default: 3).')

    parser.add_argument('--remake-basis', dest='remake_basis', type=str, default="NONE",
                        help='Toggle basis recreation mode before fitting: GPR, ALL (GLM and GPR), or NONE (Default: None)')

    parser.add_argument('-f', '--field', dest='field', type=str, required=True,
                        help='Field name to compare reference and model results on. Required.')

    parser.set_defaults(func=function)
