import os
import subprocess
from pathlib import Path

import sphinx_rtd_theme

extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.autosummary",
    "sphinx.ext.coverage",
    "sphinx.ext.doctest",
    "sphinx.ext.extlinks",
    "sphinx.ext.ifconfig",
    "sphinx.ext.napoleon",
    "sphinx.ext.todo",
    "sphinx.ext.viewcode",
]
source_suffix = ".rst"
master_doc = "index"
project = "history_matching"
year = "2017-2023"
author = "Dan Klein, Rafael Nunez, Christopher Lorton, et al."
copyright = f"{year}, {author}"
version = release = "0.1.0"

pygments_style = "trac"
templates_path = ["."]
extlinks = {
    "issue": ("https://github.com/clorton/history_matching/issues/%s", "#"),
    "pr": ("https://github.com/clorton/history_matching/pull/%s", "PR #"),
}
# on_rtd is whether we are on readthedocs.org
on_rtd = os.environ.get("READTHEDOCS", None) == "True"

if not on_rtd:  # only set the theme if we are building docs locally
    html_theme = "sphinx_rtd_theme"

html_use_smartypants = True
html_last_updated_fmt = "%b %d, %Y"
html_split_index = False
html_sidebars = {
    "**": ["searchbox.html", "globaltoc.html", "sourcelink.html"],
}
html_short_title = f"{project}-{version}"

napoleon_use_ivar = True
napoleon_use_rtype = False
napoleon_use_param = False

############################## IDM specific code ##############################

exclude_patterns = ["Thumbs.db", ".DS_Store", "setup.rst", "og_cut.rst", "reference/index.rst"]

# Remove "modules.rst" from the "api" directory
DOCS_DIR = Path(__file__).parent.absolute()
print(f"DOCS_DIR: {DOCS_DIR}")
modules_file = Path(__file__).parent.absolute() / "api" / "modules.rst"
if modules_file.exists():
    modules_file.unlink()
# Remove "history_matching*.rst" from the "api" directory
for file in (DOCS_DIR / "api").glob("history_matching*.rst"):
    file.unlink()

# Invoke `sphinx-apidoc` to generate the API api

subprocess.check_output(["sphinx-apidoc", "-f", "-e", "-M", "-o", "./api", "../src"], cwd=DOCS_DIR)

# Replace first two lines of "api/modules.rst" with the following:
# =============
# API reference
# =============
with modules_file.open() as f:
    lines = f.readlines()  # read all lines

header = [
    "=============\n",
    "API reference\n",
    "=============\n",
]

with modules_file.open("w") as f:
    f.writelines(header)  # write the new lines
    f.writelines(lines[2:])  # write the rest of the lines, skipping the first two

# -- General configuration ------------------------------------------------

# clorton tags.add("history-matching")

extensions.extend(
    [
        "sphinx.ext.mathjax",
        "sphinx.ext.githubpages",
        # 'sphinx.ext.autodoc',
        # 'sphinx.ext.napoleon',
        # 'sphinx.ext.todo',
        "plantweb.directive",
        "sphinxcontrib.programoutput",
        "sphinx.ext.intersphinx",
        "sphinxext.remoteliteralinclude",
        "sphinx_copybutton",
        "myst_parser",
    ]
)

plantuml = "plantweb"

autodoc_default_options = {"member-order": "bysource", "members": None, "exclude-members": "__all__"}

autodoc_mock_imports = []

napoleon_google_docstring = True
# napoleon_numpy_docstring = True

# Add any paths that contain templates here, relative to this directory.
templates_path = ["_templates"]

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
# import history_matching

# # The short X.Y version.
# version = history_matching.__version__
# The full version, including alpha/beta/rc tags.
# release = u'1.0'

# The language for content autogenerated by Sphinx. Refer to docs for a list of supported languages.
language = "en"

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = "sphinx"

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = False

# RST epilog is added to the end of every topic. Useful for replace directives to use across the docset.
rst_epilog = "\n.. include:: /variables.txt"

# -- MyST parser configuration to include md files
suppress_warnings = ["myst.header", "myst.iref_missing"]

# -- Options for HTML output ----------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the docs for a list of builtin themes.
html_theme = "sphinx_rtd_theme"

# Add any paths that contain custom themes here, relative to this directory.
html_theme_path = [sphinx_rtd_theme.get_html_theme_path()]

# The name of an image file (relative to this directory) to place at the top of the sidebar.
html_logo = "images/IDM_white.png"

# The name of an image file (relative to this directory) to use as a favicon of the docs.
# This file should be a Windows icon file (.ico) being 16x16 or 32x32 pixels large.
html_favicon = "images/favicon.ico"

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ["_static"]

html_context = {"css_files": ["_static/theme_overrides.css", "_static/copy_button.css"]}

html_js_files = ["show_block_by_os.js"]

# If not None, a 'Last updated on:' timestamp is inserted at every page
# bottom, using the given strftime format.
# The empty string is equivalent to '%b %d, %Y'.
#
# html_last_updated_fmt = None

# If true, SmartyPants will be used to convert quotes and dashes to
# typographically correct entities.
#
# html_use_smartypants = True

# Custom sidebar templates, maps document names to template names.
#
# html_sidebars = {}

# Additional templates that should be rendered to pages, maps page names to
# template names.
#
# html_additional_pages = {}

# If false, no module index is generated.
#
# html_domain_indices = True

# If false, no index is generated.
#
# html_use_index = True

# If true, the index is split into individual pages for each letter.
#
# html_split_index = False

# If true, links to the reST sources are added to the pages.
#
html_show_sourcelink = False

# If true, "Created using Sphinx" is shown in the HTML footer. Default is True.
#
html_show_sphinx = False

# If true, "(C) Copyright ..." is shown in the HTML footer. Default is True.
#
# html_show_copyright = True

# If true, an OpenSearch description file will be output, and all pages will
# contain a <link> tag referring to it.  The value of this option must be the
# base URL from which the finished HTML is served.
#
html_use_opensearch = "www.docs.idmod.org"

# This is the file name suffix for HTML files (e.g. ".xhtml").
# html_file_suffix = None

# Language to be used for generating the HTML full-text search index.
# Sphinx supports the following languages:
#   'da', 'de', 'en', 'es', 'fi', 'fr', 'hu', 'it', 'ja'
#   'nl', 'no', 'pt', 'ro', 'ru', 'sv', 'tr', 'zh'
#
# html_search_language = 'en'

# A dictionary with options for the search language support, empty by default.
# 'ja' uses this config value.
# 'zh' user can custom change `jieba` dictionary path.
#
# html_search_options = {'type': 'default'}

# The name of a javascript file (relative to the configuration directory) that
# implements a search results scorer. If empty, the default will be used.
#
# html_search_scorer = 'scorer.js'

# Output file base name for HTML help builder.
htmlhelp_basename = "history-matching"

# -- Options for LaTeX output ---------------------------------------------

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    #
    # 'papersize': 'letterpaper',
    # The font size ('10pt', '11pt' or '12pt').
    #
    # 'pointsize': '10pt',
    # Additional stuff for the LaTeX preamble.
    #
    # 'preamble': '',
    # Latex figure (float) alignment
    #
    # 'figure_align': 'htbp',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    (master_doc, "history_matching-docs.tex", "History Matching", "Christopher Lorton", "manual"),
]

# The name of an image file (relative to this directory) to place at the top of
# the title page.
#
# latex_logo = None

# For "manual" documents, if this is true, then toplevel headings are parts,
# not chapters.
#
# latex_use_parts = False

# If true, show page references after internal links.
#
# latex_show_pagerefs = False

# If true, show URL addresses after external links.
#
# latex_show_urls = False

# Documents to append as an appendix to all manuals.
#
# latex_appendices = []

# It false, will not define \strong, \code,     itleref, \crossref ... but only
# \sphinxstrong, ..., \sphinxtitleref, ... To help avoid clash with user added
# packages.
#
# latex_keep_old_macro_names = True

# If false, no module index is generated.
#
# latex_domain_indices = True


# -- Options for manual page output ---------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [(master_doc, "history_matching-docs", "History Matching", [author], 1)]

# If true, show URL addresses after external links.
#
man_show_urls = True

# -- Options for Texinfo output -------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (master_doc, "history_matching-docs", "History Matching", author, "Christopher Lorton", "Implementation of Bayesian History Matching, in Python, for model calibration.", "Miscellaneous"),
]

# Documents to append as an appendix to all manuals.
#
# texinfo_appendices = []

# If false, no module index is generated.
#
# texinfo_domain_indices = True

# How to display URL addresses: 'footnote', 'no', or 'inline'.
#
# texinfo_show_urls = 'footnote'

# If true, do not generate a @detailmenu in the "Top" node's menu.
#
# texinfo_no_detailmenu = False


# Example configuration for intersphinx: refer to the Python standard library.
# intersphinx_mapping = {'https://docs.python.org/': None}

intersphinx_mapping = {
    "python": ("https://docs.python.org/3", None),
    "idmtools": ("https://docs.idmod.org/projects/idmtools/en/latest/", None),
    "idmtools-calibra": ("https://docs.idmod.org/projects/idmtools_calibra/en/latest/", None),
}
