import pandas as pd
import os, sys
import errno

from dtk.utils.analyzers.BaseShelveAnalyzer import BaseShelveAnalyzer

DAYS_PER_YEAR = 365.

class PrevalenceAnalyzer(BaseShelveAnalyzer):

    def __init__(self, name, weight, 
                force_apply = False,
                force_combine = True,
                basedir = '.',
                verbose = False,
                **kwargs):

        super(PrevalenceAnalyzer, self).__init__(force_apply, force_combine, verbose)

        self.filenames += [ os.path.join('output', 'InsetChart.json') ]
        self.parse = True # Set to False to not have dtk-tools parse the file, just provide it raw
        self.basedir = basedir

        self.count = {}
        self.sim_ids = []
        self.num_outstanding = 0

        self.name = name
        self.weight = weight
        self.site = None
        self.setup = {}

        if not os.path.isdir(self.basedir):
            PrevalenceAnalyzer.mkdir_p(self.basedir)


    @staticmethod
    def mkdir_p(path):
        try:
            os.makedirs(path)
        except FileExistsError as exc:  # Python >2.5
            if exc.errno == errno.EEXIST and os.path.isdir(path):
                pass
            else:
                raise

    def filter(self, sim_metadata):
        self.workdir = os.path.join(self.basedir, self.exp_id)
        if not os.path.isdir(self.workdir):
            PrevalenceAnalyzer.mkdir_p(self.workdir)

        sim_id = sim_metadata['sim_id']
        self.sim_ids.append(sim_id)
        self.num_outstanding += 1

        if not self.shelve_file:    # Want this in the base class, but don't know exp_id at __init__
            self.shelve_file = os.path.join(self.workdir, '%s.db' % self.__class__.__name__) # USE ID instead?

        ret = super(PrevalenceAnalyzer, self).filter(self.shelve_file, sim_metadata)

        if not ret and self.verbose:
            self.num_outstanding -= 1
            print('Skipping simulation %s because already in shelve' % str(sim_id))

        return ret


    def apply(self, parser):
        super(PrevalenceAnalyzer, self).apply(parser)

        J = parser.raw_data[self.filenames[0]]

        header = J['Header']
        dt = float(header['Simulation_Timestep'])
        base_year = header['Base_Year'] if 'Base_Year' in header else 0
        steps = header ['Timesteps']

        prevalence = [x for x in J['Channels']['Infected']['Data'] ]
        year = [base_year + (s+1) * dt/DAYS_PER_YEAR for s in range(steps)]
        timestep = range(steps)

        # If analyzing simulation not generated by itertool, __sample_index__ will not be in tags
        # Instead, use Run_Number
        sample = parser.sim_data.get('__sample_index__')
        if sample is None:
            sample = parser.sim_data.get('Run_Number')

        data = pd.DataFrame({'Year':year, 'Timestep': timestep, 'Prevalence':prevalence})
        data.index.name = 'Index'

        shelve_data = {
            'Data': data,
            'Sim_Id': parser.sim_id,
            'Sample': sample
        }
        self.shelve_apply( parser.sim_id, shelve_data)

        self.num_outstanding -= 1
        if self.verbose:
            print('Progress: %d of %d (%.1f%%) [%.2f MB cached].'%(len(self.sim_ids)-self.num_outstanding, len(self.sim_ids), 100*(len(self.sim_ids)-self.num_outstanding) / float(len(self.sim_ids)), sys.getsizeof(shelve_data)/8.0/1024.0))


    def combine(self, parsers):
        if self.verbose:
            print("combine")

        shelved_data = super(PrevalenceAnalyzer, self).combine(parsers)

        if shelved_data is not None:
            if self.verbose:
                print('Combine from cache')
            self.data = shelved_data['Data']
            return

        selected = [ self.shelve[str(sim_id)]['Data'] for sim_id in self.sim_ids ]
        keys = [ (self.shelve[str(sim_id)]['Sample'], self.shelve[str(sim_id)]['Sim_Id'])
            for sim_id in self.sim_ids ]

        self.data = pd.concat( selected, axis=0,
                            keys=keys,
                            names=['Sample', 'Sim_Id'] )

        self.data.reset_index(level='Index', drop=True, inplace=True)

        try:
            self.shelve_combine({'Data':self.data})
        except:
            print("shelve_combine didn't work, sorry")


    def finalize(self):
        fn = 'Results_%s.csv'%self.__class__.__name__
        print('--> Writing %s'%fn)
        output = self.data.reset_index().groupby(['Sample', 'Sim_Id', 'Year']).sum()

        results_filename = os.path.join(self.working_dir, self.basedir, self.exp_id, fn)
        output.to_csv(results_filename)

        self.sim_ids = []

        print('--> super finalize')
        # Close the shelve file, among other little things.  Can take a long time:
        super(PrevalenceAnalyzer, self).finalize()
